<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\hearts.png" />
    <None Remove="Resources\Images\icon.ico" />
    <None Remove="Resources\Images\leopard.jpg" />
    <None Remove="Resources\Images\space.jpg" />
    <None Remove="Resources\Sounds\click.mp3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Sounds\click.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Cursors\" />
    <Folder Include="Resources\Fonts\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\hearts.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\leopard.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\space.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Dialogs\Dictionary1.xaml.cs">
      <Generator>MSBuild:Compile</Generator>
    </Compile>
  </ItemGroup>

</Project>
